import React, { useState, useEffect, useCallback } from 'react';
import { Report } from '../../api/types';
import { reportsApi } from '../../api/client';
import { useStudent } from '../../context/StudentContext';
import { Badge } from '../common/Badge';
import { SpeechSpeakerButton } from '../common/SpeechSpeakerButton';
import {
  FileText,
  Sparkles,
  Loader2,
  Calendar,
  CheckCircle2,
  Lightbulb,
  Activity,
} from 'lucide-react';
import { clsx } from 'clsx';

export const ReportsView: React.FC = () => {
  const { currentStudent } = useStudent();
  const studentId = currentStudent?._id;

  const [reports, setReports] = useState<Report[]>([]);
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);

  const fetchReports = useCallback(async () => {
    if (!studentId) return;
    try {
      setLoading(true);
      const list = await reportsApi.list(studentId);
      setReports(list);
      setSelectedReport((prev) => (prev ? prev : list.length > 0 ? list[0] : null));
    } catch (err: any) {
      console.error('Failed to load reports:', err);
    } finally {
      setLoading(false);
    }
  }, [studentId]);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  const handleGenerateReport = async () => {
    if (!studentId || isGenerating) return;
    try {
      setIsGenerating(true);
      const newReport = await reportsApi.generate(studentId, 'overall');
      setReports((prev) => [newReport, ...prev]);
      setSelectedReport(newReport);
    } catch (err: any) {
      console.error('Report generation failed:', err);
      alert(`Report generation error: ${err?.message || 'Failed to generate report'}`);
    } finally {
      setIsGenerating(false);
    }
  };

  if (!currentStudent) {
    return (
      <div className="p-8 text-center bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800">
        <p className="text-sm text-slate-500">Please select a student to view progress reports.</p>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fadeIn pb-8">
      {/* Header & Generate Button */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-6 bg-gradient-to-r from-purple-900/10 via-brand-900/10 to-indigo-900/10 rounded-3xl border border-purple-200 dark:border-purple-800/60">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <FileText className="w-6 h-6 text-purple-600 dark:text-purple-400" />
            <h2 className="text-xl md:text-2xl font-extrabold text-slate-900 dark:text-white">
              AI Progress & Diagnostic Reports
            </h2>
          </div>
          <p className="text-xs md:text-sm text-slate-600 dark:text-slate-400 max-w-xl">
            Comprehensive diagnostic summaries generated by our multi-agent AI system analyzing cognitive memory, speech stability, phonological accuracy, and emotional engagement.
          </p>
        </div>

        <button
          type="button"
          onClick={handleGenerateReport}
          disabled={isGenerating}
          className="flex items-center justify-center gap-2 px-6 py-3 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 text-white font-bold text-xs md:text-sm rounded-2xl shadow-lg hover:shadow-xl transition-all shrink-0 cursor-pointer disabled:cursor-not-allowed"
        >
          {isGenerating ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              <span>AI Agents are Synthesizing Report...</span>
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4" />
              <span>Generate Fresh AI Report</span>
            </>
          )}
        </button>
      </div>

      {loading ? (
        <div className="py-16 text-center space-y-3">
          <Loader2 className="w-8 h-8 animate-spin text-purple-600 mx-auto" />
          <p className="text-xs text-slate-500 font-medium">Loading reports history...</p>
        </div>
      ) : reports.length === 0 ? (
        <div className="py-16 text-center bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 space-y-3">
          <FileText className="w-12 h-12 text-slate-300 dark:text-slate-600 mx-auto" />
          <h3 className="text-lg font-bold text-slate-800 dark:text-slate-200">
            No Reports Generated Yet
          </h3>
          <p className="text-xs md:text-sm text-slate-500 max-w-md mx-auto">
            Click the "Generate Fresh AI Report" button above to synthesize {currentStudent.name}'s first comprehensive diagnostic summary!
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Reports History List Sidebar */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Report Archives ({reports.length})
            </h3>
            <div className="space-y-2 max-h-[600px] overflow-y-auto pr-1">
              {reports.map((report) => {
                const isSelected = selectedReport?._id === report._id;
                const dateStr = new Date(report.generated_at).toLocaleDateString(undefined, {
                  year: 'numeric',
                  month: 'short',
                  day: 'numeric',
                  hour: '2-digit',
                  minute: '2-digit',
                });

                return (
                  <div
                    key={report._id}
                    onClick={() => setSelectedReport(report)}
                    className={clsx(
                      'p-4 rounded-2xl border transition-all cursor-pointer select-none space-y-2',
                      isSelected
                        ? 'bg-purple-50 dark:bg-purple-950/60 border-purple-500 shadow-sm ring-1 ring-purple-500'
                        : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 hover:border-purple-300'
                    )}
                  >
                    <div className="flex items-center justify-between">
                      <Badge variant="purple" size="sm">
                        {report.period}
                      </Badge>
                      <span className="text-[11px] text-slate-400 flex items-center gap-1 font-mono">
                        <Calendar className="w-3 h-3" />
                        {dateStr}
                      </span>
                    </div>

                    <div className="text-xs text-slate-600 dark:text-slate-300 line-clamp-2">
                      {report.recommendations?.[0] || 'AI Cognitive & Behavioral Synthesis'}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Selected Report Full Viewer */}
          {selectedReport && (
            <div className="lg:col-span-2 p-6 md:p-8 bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-md space-y-6 animate-fadeIn">
              {/* Report Header */}
              <div className="flex items-start justify-between gap-4 border-b border-slate-100 dark:border-slate-800 pb-5">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <Badge variant="purple" size="md">
                      <span>Period: {selectedReport.period}</span>
                    </Badge>
                    <span className="text-xs text-slate-400 font-mono">
                      Generated:{' '}
                      {new Date(selectedReport.generated_at).toLocaleString()}
                    </span>
                  </div>
                  <h3 className="text-xl md:text-2xl font-extrabold text-slate-900 dark:text-white">
                    Learner Evaluation Summary: {currentStudent.name}
                  </h3>
                </div>

                <SpeechSpeakerButton
                  text={`Progress Report for ${currentStudent.name}. ${selectedReport.recommendations.join(
                    '. '
                  )}`}
                  size="md"
                  variant="filled"
                />
              </div>

              {/* Summary Metrics Grid */}
              {selectedReport.summary && Object.keys(selectedReport.summary).length > 0 && (
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                  {Object.entries(selectedReport.summary).map(([key, val], idx) => (
                    <div
                      key={idx}
                      className="p-3.5 bg-slate-50 dark:bg-slate-800/60 rounded-2xl border border-slate-200 dark:border-slate-700/80"
                    >
                      <span className="text-xs text-slate-500 uppercase tracking-wider block font-semibold truncate">
                        {key.replace(/_/g, ' ')}
                      </span>
                      <span className="text-base font-extrabold text-slate-800 dark:text-slate-100">
                        {typeof val === 'number' ? `${Math.round(val)}%` : String(val)}
                      </span>
                    </div>
                  ))}
                </div>
              )}

              {/* Detailed Findings with Severity */}
              {selectedReport.detailed_findings &&
                selectedReport.detailed_findings.length > 0 && (
                  <div className="space-y-3">
                    <h4 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
                      <Activity className="w-4 h-4 text-brand-600" />
                      <span>Clinical & Cognitive Findings</span>
                    </h4>

                    <div className="space-y-2">
                      {selectedReport.detailed_findings.map((item, idx) => {
                        const sevVariant =
                          item.severity === 'high'
                            ? 'danger'
                            : item.severity === 'medium'
                            ? 'warning'
                            : 'secondary';

                        return (
                          <div
                            key={idx}
                            className="p-4 bg-slate-50 dark:bg-slate-800/60 rounded-2xl border border-slate-200 dark:border-slate-700/80 flex items-start justify-between gap-3"
                          >
                            <div className="space-y-1">
                              <span className="text-xs font-bold text-slate-500 dark:text-slate-400">
                                {item.category}
                              </span>
                              <p className="text-xs md:text-sm text-slate-800 dark:text-slate-200 leading-relaxed">
                                {item.finding}
                              </p>
                            </div>
                            <Badge variant={sevVariant} size="sm">
                              {item.severity}
                            </Badge>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

              {/* Recommendations */}
              {selectedReport.recommendations &&
                selectedReport.recommendations.length > 0 && (
                  <div className="p-5 bg-gradient-to-r from-purple-50 to-brand-50 dark:from-purple-950/40 dark:to-brand-950/40 rounded-2xl border border-purple-200 dark:border-purple-800/70 space-y-3">
                    <h4 className="text-sm font-bold text-purple-900 dark:text-purple-200 flex items-center gap-2">
                      <Lightbulb className="w-4 h-4 text-amber-500" />
                      <span>Actionable Recommendations for Educators & Parents</span>
                    </h4>

                    <ul className="space-y-2 text-xs md:text-sm text-slate-800 dark:text-slate-200">
                      {selectedReport.recommendations.map((rec, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <CheckCircle2 className="w-4 h-4 text-purple-600 dark:text-purple-400 shrink-0 mt-0.5" />
                          <span>{rec}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
            </div>
          )}
        </div>
      )}
    </div>
  );
};
